### ISSUE TITLE
(A) Genome (fast)

### ISSUE THREAD

**Issue by mrshu** [fmfi-genomika/genomikaMalGlo#1]

**Comment by mrshu** [comment]
@vidriduch @matejkrajcovic This should be done already, right?

**Comment by vidriduch** [comment]
@mrshu yes - well, sort of. Meaning everything should be setup. But when we followed the setup we also create new track which is wrongly defined in trackDb file. Also before commiting this basic changes to main repo. The trackDb file should be cleaned since this one was for now copied out of some previous project and contains yet not existing tracks. But these are minor changes not influencing work of others. If anyone will be adding new track and sees entry in the trackDb file he/she can freely remove it.

**Comment by mrshu** [comment]
@vidriduch ok, if this trackDb problem is not influencing the work of others, can we close this issue?

If so, please feel free to do so.

Thanks!

**Comment by mrshu** [comment]
@vidriduch @matejkrajcovic ping

**Comment by mrshu** [comment]
@vidriduch @matejkrajcovic I am sorry for pinging you again, but as far as I understand this seems to be done. Can we please mark it as such?

Thanks!

**Comment by matejkrajcovic** [comment]
@mrshu I will fix minor issues later today.

**Comment by mrshu** [comment]
Thanks @matejkrajcovic, should you have enough bandwidth, feel free to pick something else from https://github.com/fmfi-genomika/genomikaMalGlo/projects/1

**Comment by vidriduch** [comment]
@matejkrajcovic @mrshu I left it open utill I resolved metioned issues, but it seems to be closed. The problem with `gc5Base` track should be fixed and pretty much empty fresh `trackDb.ra` should be present on the server. I created a pull request with changes to mail repo https://github.com/fmfi-genomika/genomika-2017/pull/4. Feel free to comment on it. Also you can checkout working gc5Base track and check if it is correct. If any issues would come up please let me know.

**Comment by lej-la** [comment]
I would expect to find `malGlo1.fa` in `/gbdb/malGlo1/` similarly to `/gbdb/malSym1/malSym1.fa`, but there's no such file.
I need it for https://github.com/fmfi-genomika/genomikaMalSym/issues/8
Could you please take a look at it?

**Comment by matuszelenak** [comment]
I think what you are looking for is `/gbdb/malGlo1/GCF_000181695.1_ASM18169v1_genomic.fna`
Yes, we should rename it

**Comment by lej-la** [comment]
Thanks!
