### ISSUE TITLE
(K) Conservation by phyloP (medium, needs A,I,J)

### ISSUE THREAD

**Issue by mrshu** [fmfi-genomika/genomikaMalGlo#11]
- Based on multiple alignment from part J, find which positions are conserved in evolution (the result is a numerical level of conservation per position in a wiggle format)
- See tracks Align. Cons. (L) and Multiz. Cons. (L) in sacCer3 browser (here we want only one track)
- Use the same tree as in I
- https://github.com/fmfi-genomika/genomika-2017/wiki/PhyloP-tracks

**Comment by mrshu** [comment]
@ViRPo Anything I can help you with here?

**Comment by virpo** [comment]
@mrshu I am getting there, no hiccups yet
I will try to finish it before our meetup, and if I have any problems, I will ask you there :)

**Comment by virpo** [comment]
I ran into an error, that I was not able to resolve after trying for an hour

I described what steps I took here: https://github.com/fmfi-genomika/genomikaMalGlo/wiki/PhyloP-tracks

Do you have any tips or have you seen it before? cc @mrshu @bbrejova

**Comment by Zygro** [comment]
Same in (L) #12

**Comment by virpo** [comment]
@Zygro I finally found how to resolve this!
In my case, I had a single .maf file which contained multiple .maf files combined
In order to make it work, I had to either split it into multiple separate files or just use .maf that is already split by other group located in /data/malSym/taskK/chrom_split/
I hope this helps

**Comment by virpo** [comment]
Alright, finally resolved all the issues

Documentation: https://github.com/fmfi-genomika/genomikaMalGlo/wiki/(K)-PhyloP-track
